//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfileApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> Height { get; set; }
    }
}
